[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",       # pycodestyle
    "F",       # pyflakes
    "ISC",     # flake8-implicit-str-concat
    "PIE",     # flake8-pie
]
ignore = [
    "ISC001",  # incompatible with ruff format
]

[tool.black]
line-length = 120

[tool.mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_decorators = true
files = "namcap.py,Namcap/**/*.py"
ignore_missing_imports = true
implicit_reexport = false
namespace_packages = true
no_implicit_optional = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_ignores = true
