[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",       # pycodestyle
    "F",       # pyflakes
    "ISC",     # flake8-implicit-str-concat
]
ignore = [
    "ISC001",  # incompatible with ruff format
]

[tool.black]
line-length = 120
